# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dd6aea38846ed3a8a903395879b47556ebc94acd34a893a3769c2f04e880798937dcccb3ca3c525629d6f33ba60d3513a8465334ed9173efaac73d2fbb26898

test:
  secret_key_base: 708847e2148821b4c5bba47c75ae0173b230996127f48c19692680417f3e0a8426abd1983e0ee1b55d47ca5590be1c788c4e55a2baf95daae4669d9c0cf4a05c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
